[package]
name = "wdis"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
bytes = "1.0"
papaya ="0.2.1"
byteorder= "1.5.0"
once_cell = "1.21.3"
skl = "0.22.17"